Python 3.13.14 (tags/v3.13.14:fd17997, Jun 10 2026, 13:03:48) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> from random import randrange
... 
... 
... def get_user_weapon():
...     print("\nChoose your weapon:")
...     print("1. Rock")
...     print("2. Paper")
...     print("3. Scissors")
... 
...     choice = int(input("Enter your choice (1-3): "))
...     return choice
... 
... 
... def get_opponent_weapon():
...     opponent = randrange(1, 4)  # Generates 1, 2, or 3
...     return opponent
... 
... 
... def determine_winner(user, opponent):
...     weapons = {1: "Rock", 2: "Paper", 3: "Scissors"}
... 
...     print("\nYou chose:", weapons[user])
...     print("Opponent chose:", weapons[opponent])
... 
...     if user == opponent:
...         print("The game has resulted in a tie.")
... 
...     elif user == 1 and opponent == 3:
...         print("Rock beats Scissors. You win!")
... 
...     elif user == 3 and opponent == 2:
...         print("Scissors beats Paper. You win!")
... 
...     elif user == 2 and opponent == 1:
...         print("Paper beats Rock. You win!")
... 
...     else:
...         print("You lose!")
... 
... 
... def main():
...     continue_playing = "Y"
... 
...     while continue_playing.upper() == "Y":
...         user_weapon = get_user_weapon()
...         opponent_weapon = get_opponent_weapon()
... 
...         determine_winner(user_weapon, opponent_weapon)
... 
...         continue_playing = input("\nWould you like to play again? (Y/N): ")
... 
    print("\nCompleted by, Asekun Shackleford")


if __name__ == "__main__":
